.TH MCMFMT 1
.SH NAME
mcmfmt \- sets bold and underline for mail files
.br
.SH "DESCRIPTION"
.B mcmfmt
is a program for internal use by the Midnight Commander only. It sets
bold and underline for mail files.
.SH OPTIONS
There are no options for this program.
.SH "SEE ALSO"
mc(1)
.SH AUTHOR
This manual page was written by Paul Seelig <pseelig@goofy.zdv.uni-mainz.de> 
for the Debian GNU/Linux system (but may be used by others).
