#! /bin/sh /usr/share/dpatch/dpatch-run
##
## svnshell by <dwhedon@debian.org>
##
## DP: Contains r20992 from upstream trunk, which may be in 1.4.1.

@DPATCH@
--- a/tools/examples/svnshell.py
+++ b/tools/examples/svnshell.py
@@ -49,14 +49,8 @@
   def postcmd(self, stop, line):
     self._setup_prompt()
 
-  _errors = ["Huh?",
-             "Whatchoo talkin' 'bout, Willis?",
-             "Say what?",
-             "Nope.  Not gonna do it.",
-             "Ehh...I don't think so, chief."]
-
   def default(self, line):
-    print(self._errors[randint(0, len(self._errors) - 1)])
+    print "Unknown command."
 
   def do_cat(self, arg):
     """dump the contents of a file"""
