#!/bin/bash

exec >&3

echo "--- configuration ---"
if [ -x "$(which clamconf)" ]; then
  clamconf
else
  for file in clamd freshclam; do
    [ ! -f "/etc/clamav/${file}.conf" ] || cat "/etc/clamav/${file}.conf" 
  done
fi

echo
echo "--- data dir ---"
ls -l /var/lib/clamav
