.TH JADE 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
jade \- James' DSSSL Engine
.SH SYNOPSIS
.B jade
.I "[options] files ..."
.SH "DESCRIPTION"
This manual page documents briefly the
.BR jade
command.
This manual page was written for the Debian GNU/Linux distribution
(but may be used by others), because the original program does not
have a manual page.
Instead, it has documentation in HTML format; see below.
.PP
.B jade
is an implementation of the DSSSL style language.
The current version is 1.1.
.SH OPTIONS
For a complete description, see the html files.
.SH "SEE ALSO"
The programs are documented fully in
.B /usr/share/doc/jade/jade.htm
.SH AUTHOR
This manual page was written by Mark W. Eichin <eichin@kitten.gen.ma.us>,
for the Debian GNU/Linux system.
