.\"                                      Hey, EMACS: -*- nroff -*-
.TH TG-ADMIN 1 "September 2009"
.SH NAME
tg-admin \- TurboGears command line tool
.SH SYNOPSIS
\fBtg-admin\fR <\fIcommand\fR> [\fIcommand\fR] [\fIoptions\fR]
.br
.SH DESCRIPTION
The tg-admin command line tool provides commands for working with TurboGears projects. You can get a list of 
the available commands by simply running "tg-admin".

For a complete description, run \fBtg-admin [command] help\fP for each available command:

\fBi18n\fP - Manage i18n data

\fBinfo\fP - Show version info

\fBquickstart\fP - Create a new TurboGears project

\fBshell\fP - Start a Python prompt with your database available

\fBsql\fP - Run the database provider manager

\fBtoolbox\fP - Launch the TurboGears Toolbox

\fBupdate\fP - Update an existing turbogears project

.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
.TP
.B \-c, \-\-config FILENAME
Config file to use
.TP
.B \-e, \-\-egg EGG_SPEC
Run command on given Egg
.TP
.br
The official documentation is available at: \fI\%http://docs.turbogears.org/1.0/TgAdmin\fR

.SH AUTHOR
tg-admin was written by Kevin Dangoor.
.PP
This manual page was written by Federico Ceratto <federico.ceratto@gmail.com>,
for the Debian project (and may be used by others).
