debian/tmp/prefork/usr/include/apache2/* usr/include/apache2/
debian/tmp/prefork/usr/share/apache2/build/* usr/share/apache2/build/

debian/tmp/prefork/usr/include/amd64/apache2/* usr/include/amd64/apache2/
debian/tmp/prefork/usr/share/apache2/amd64/build/* usr/share/apache2/amd64/build/

# It's a perl script:
build-tree/mpm32-worker/support/apxs usr/bin/
build-tree/mpm64-worker/support/apxs usr/bin/amd64/
usr/share/man/man8/apxs2.8
