#!/bin/sh -e

action="$1"
oldversion="$2"

if [ "$action" != configure ]
  then
  exit 0
fi

test ! -f /etc/rsyncd.conf && \
	echo "pid file=/var/run/rsyncd.pid" > /etc/rsyncd.conf

#if [ -x /etc/init.d/rsync ]; then
#        update-rc.d rsync defaults >/dev/null
#        if [ -x /usr/sbin/invoke-rc.d ]; then
#                invoke-rc.d rsync restart
#        else
#                /etc/init.d/rsync restart
#        fi
#fi

exit 0
