.TH NTPQ 8 "October 7, 2006" "Network Time Protocol"
.SH NAME
ntp\-wait \- wait for NTP server to synchronize
.SH SYNOPSIS
.B ntp\-wait
[ \-f ] [ \-n \fItries\fR ] [ \-s \fIsleep\fR ] [ \-v ]
.SH DESCRIPTION
ntp\-wait waits until the locally running ntpd is in state 4 (synchronized).
This could be useful at boot time, to delay the boot sequence until after
"ntpd \-g" has set the time.
.SH OPTIONS
.TP
\-f
Force hard failure if state is unknown.
.TP
\-n \fItries\fR
Number of tries before giving up (default 1000 = 10min+)
.TP
\-s \fIsleep\fR
Seconds to sleep between tries (default 6s = 10/min)
.TP
\-v
Be verbose.
