.\" transcribed from ntp 4.2.2p3
.TH NTPTIME 8 "October 7, 2006" "Network Time Protocol"
.SH NAME
ntptime \- read kernel time variables
.SH SYNOPSIS
.B ntptime
[ \-chr ] [ \-e \fIest_error\fR ] [ \-f \fIfrequency\fR ] [ \-m \fImax_error\fR ] [ \-o \fIoffset\fR ] [ \-s \fIstatus\fR ] [ \-t \fItime_constant\fR ] 
.SH DESCRIPTION
This program is useful only with special kernels described in the A Kernel Model for Precision Timekeeping page. It reads and displays time-related kernel variables using the ntp_gettime() system call. A similar display can be obtained using the ntpdc program and kerninfo command.
.SH OPTIONS
.TP
\-c
Display the execution time of ntptime itself.
.TP
\-e \fIest_error\fR
Specify estimated error, in microseconds.
.TP
\-f \fIfrequency\fR
Specify frequency offset, in parts per million.
.TP
\-h
Display help information.
.TP
\-m \fImax_error\fR
Specify max possible errors, in microseconds.
.TP
\-o \fIoffset\fR
Specify clock offset, in microseconds.
.TP
\-r
Display Unix and NTP times in raw format.
.TP
\-s \fIstatus\fR
Specify clock status. Better know what you are doing.
.TP
\-t \fItime_constant\fR
Specify time constant, an integer in the range 0-10.
