#! /bin/sh

set -e

if [ install = "$1" -o upgrade = "$1" ]; then
    if [ -n "$2" ] && dpkg --compare-versions $2 lt 2.20-3; then
	case "$(dpkg-divert --list /usr/gnu/bin/ld)" in
	    *ld.single*)
		rm -f /usr/gnu/bin/ld
		dpkg-divert \
		  --package binutils-gold \
		  --remove --rename \
		  --divert /usr/gnu/bin/ld.single /usr/gnu/bin/ld
	esac
    fi

    dpkg-divert \
	--package binutils-gold \
	--add --rename \
	--divert /usr/gnu/bin/ld.bfd-link /usr/gnu/bin/ld
fi
