usr/share/mc/cedit.menu
usr/share/mc/*.ini
usr/share/mc/*.rc
usr/share/mc/mc.*
usr/share/mc/Syntax
usr/bin/mc*
usr/share/mc/extfs.d/*
usr/share/mc/mc*sh usr/share/mc/bin
usr/share/locale/*
usr/share/man/es/*
usr/share/man/hu/*
usr/share/man/it/*
usr/share/man/man1/*
usr/share/man/pl/*
usr/share/man/ru/*
usr/share/man/sr/*
usr/share/mc/mc.*
usr/share/mc/skins/*.ini
usr/share/mc/syntax/*.syntax
debian/extra/icon/mc.xpm usr/share/pixmaps
debian/lintian/mc usr/share/lintian/overrides
