#!/bin/sh
set -e

case "$1" in
	configure|abort-upgrade)
		update-alternatives --install /usr/bin/view view /usr/bin/mcview 25 \
			--slave /usr/share/man/man1/view.1.gz view.1.gz /usr/share/man/man1/mcview.1.gz
		update-alternatives --install /usr/bin/editor editor /usr/bin/mcedit 25 \
			--slave /usr/share/man/man1/editor.1.gz editor.1.gz /usr/share/man/man1/mcedit.1.gz
	;;
esac

#DEBHELPER#

exit 0
