.TH LIBTOOLIZE 1 "August 2003" "Library Support" "User Manuals"
.SH NAME
libtoolize \- add libtool support to your package
.SH SYNOPSIS
.B libtoolize
.I "[OPTION]..."
.SH "DESCRIPTION"
The `libtoolize' program provides a standard way to add libtool
support to your package.  In the future, it may implement better usage
checking, or other features to make libtool even easier to use.
.SH "OPTIONS"
libtoolize accepts the following options:
.TP
.B \-\-automake
Work silently, and assume that Automake libtool support is used.

`libtoolize --automake' is used by Automake to add libtool files to
your package, when `AC_PROG_LIBTOOL' appears in your `configure.in'.
.TP
.B \-\-copy, \-c
Copy files from the libtool data directory rather than creating
symlinks.
.TP
.B \-\-debug
Enable verbose shell tracing
.TP
.B \-\-dry-run, \-n
Don't run any commands that modify the file system, just print them
out.
.TP
.B \-\-force, \-f
Replace existing libtool files.  By default, `libtoolize' won't
overwrite existing files.
.TP
.B \-\-help
Display a help message and exit.
.TP
.B \-\-ltdl
Install libltdl in a subdirectory of your package.
.TP
.B \-\-ltdl\-tar
Add the file `libltdl.tar.gz' to your package.
.TP
.B \-\-version
Print `libtoolize' version information and exit.

If `libtoolize' detects an explicit call to `AC_CONFIG_AUX_DIR'
in your `configure.in', it will put the files in the specified directory.

`libtoolize' displays hints for adding libtool support to your
package, as well.

.SH "SEE ALSO"
.BR libtool (1),
.BR automake (1)
.br
`libtool', `libtoolize' and `automake' are fully documented via the
Info system.
.SH AUTHOR
This manual page was written by Frederic Lepied <Lepied@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
It was updated by Ossama Othman <ossama@debian.org> and updated for
Libtool 1.5 by Scott James Remnant <scott@netsplit.com>.
