#!/bin/sh
set -e

if [ "$1" = purge ] || [ "$1" = remove ]; then
  rm -rf /var/run/screen
#  rm -f  /etc/rcS.d/S70screen*  
fi

if [ "$1" = disappear ]; then
  remove-shell /usr/bin/screen || true
fi

#DEBHELPER#
