#!/bin/sh

set -e 

update-alternatives --install /usr/include/mpi mpi /usr/include/lam 30 \
    --slave /usr/lib/libmpi.so libmpi.so /usr/lib/liblam.so \
    --slave /usr/lib/libmpio.so libmpio.so /usr/lib/liblamio.so \
    --slave /usr/lib/libmpi++.so libmpi++.so /usr/lib/liblam++.so \
    --slave /usr/lib/libmpi.a libmpi.a /usr/lib/liblam.a \
    --slave /usr/lib/libmpio.a libmpio.a /usr/lib/liblamio.a \
    --slave /usr/lib/libmpi++.a libmpi++.a /usr/lib/liblam++.a \
    --slave /usr/bin/mpicc mpicc /usr/bin/mpicc.lam \
    --slave /usr/share/man/man1/mpicc.1.gz mpicc.1.gz /usr/share/man/man1/mpicc.lam.1.gz \
    --slave /usr/bin/mpif77 mpif77 /usr/bin/mpif77.lam \
    --slave /usr/share/man/man1/mpif77.1.gz mpif77.1.gz /usr/share/man/man1/mpif77.lam.1.gz \
    --slave /usr/bin/mpiCC mpiCC /usr/bin/mpic++.lam \
    --slave /usr/share/man/man1/mpiCC.1.gz mpiCC.1.gz /usr/share/man/man1/mpiCC.lam.1.gz \
    --slave /usr/bin/mpic++ mpic++ /usr/bin/mpic++.lam \
    --slave /usr/share/man/man1/mpic++.1.gz mpic++.1.gz /usr/share/man/man1/mpic++.lam.1.gz

#DEBHELPER#

exit 0
