set runtimepath=~/.vim,/var/lib/vim/addons,/usr/share/vim/vimfiles,/usr/share/vim/vim73,/usr/share/vim/vimfiles/after,/var/lib/vim/addons/after,~/.vim/after
set nocompatible
set backspace=indent,eol,start
set history=100
set nomodeline
set pastetoggle=<F5>
set encoding=utf-8
set number
set sw=4
set expandtab
set tabstop=4
set hlsearch
set wrap
set mouse=a
set linebreak
set sm
set ruler
set showcmd
set incsearch
set ai

set suffixes=.bak,~,.swp,.o,.info,.aux,.log,.dvi,.bbl,.blg,.brf,.cb,.ind,.idx,.ilg,.inx,.out,.toc
if &term =~ "xterm-debian" || &term =~ "xterm-xfree86"
  set t_Co=16
  set t_Sf=[3%dm
  set t_Sb=[4%dm
endif

if has('gui_running')
  " Make shift-insert work like in Xterm
  map <S-Insert> <MiddleMouse>
  map! <S-Insert> <MiddleMouse>
endif
syntax on

if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

if has("autocmd")
  filetype plugin indent on
endif

colorscheme murphy
set laststatus=2
set statusline=%F\ [%Y,\ %{&ff}]\ %=\ %l:%c\ (%p%%)\ \|\ %{strftime(\"%Y-%m-%d,\ %H:%M\")}


augroup filetypedetect
au BufNewFile,BufRead *.asy     setf asy
augroup END

set iskeyword+=_

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
