.TH LIBTOOL 1  "August 2003" "Library Support" "User Manuals"
.SH NAME
libtool \- Provide generalized library-building support services.
.SH SYNOPSIS
.B libtool
.BI [ OPTION ] ...
.BI [ MODE\-ARG ] ...
.SH "DESCRIPTION"
The `libtool' program provides a standard way to generate both static
and shared libraries.  It hides the complexities of platform\-specific
library generation behind an interface that is the same across all
platforms supported by libtool.
.SH "OPTIONS"
libtool accepts the following options:
.TP
.B \-\-config
Display libtool configuration variables and exit.
.TP
.B \-\-debug
Dump a trace of shell script execution to standard output.  This
produces a lot of output, so you may wish to pipe it to `less' (or
`more') or redirect to a file.
.TP
.BI \-n | \-\-dry-run
Don't create, modify, or delete any files, just show what commands
would be executed by `libtool'.
.TP
.B \-\-features
Display basic configuration options.  This provides a way for packages
to determine whether shared or static libraries will be built.
.TP
.B \-\-finish
Same as
.BR \-\-mode=finish .
.TP
.B \-\-help
Display a help message and exit.  If
.BI \-\-mode= MODE
is specified, then detailed help for
.I MODE
is displayed.
.TP
.BI \-\-mode= MODE
Use
.I MODE
as the operation mode.  By default, the operation mode is inferred
from the
.IR MODE\-ARGS .

If
.I MODE
is specified, it must be one of the following:
.IP
.B clean
Remove files from the build directory
.IP
.B compile
Compile a source file into a `libtool' object.
.IP
.B execute
Automatically set the library path, then run a program.
.IP
.B finish
Complete the installation of libtool libraries.
.IP
.B install
Install libraries or executables.
.IP
.B link
Create a library or an executable.
.IP
.B uninstall
Remove libraries from an installed directory.
.TP
.B \-\-quiet
Same as `\-\-silent'.
.TP
.B \-\-silent
Don't print informational messages.
.TP
.B \-\-tag=TAG
Use configuration variables from tag 
.I TAG
.TP
.B \-\-version
Print version information.
.P
The
.I MODE\-ARGS
are a variable number of arguments, depending on the selected
operation mode.  In general, each
.I MODE\-ARG
is interpreted by programs libtool invokes, rather than libtool itself.
.SH "SEE ALSO"
.BR libtoolize (1),
.BR automake (1)
.br
`libtool', `libtoolize' and `automake' are fully documented via the
Info system.
.SH AUTHOR
This manual page was created by Ossama Othman <ossama@debian.org>.  It
is based on the "Invoking Libtool" menu entry in the `libtool' TEXINFO
documentation, and the output from the
.B \-\-help
option.  It was updated for Libtool 1.5 by
Scott James Remnant <scott@netsplit.com>.
