.TH ntpdate-debian 8
.SH NAME
ntpdate-debian \- set the date and time via NTP
.SH SYNOPSIS
.B ntpdate-debian
.RB [\| \-bBdoqsuv \|] 
.RB [\| \-a 
.IR key \|] 
.RB [\| \-e 
.IR authdelay \|] 
.RB [\| \-k 
.IR keyfile \|]
.RB [\| \-o
.IR version \|]
.RB [\| \-p
.IR samples \|]
.RB [\| \-t
.IR timeout \|]
.SH DESCRIPTION
.B ntpdate-debian
is identical to
.BR ntpdate (8)
except that it uses the configuration in
.I /etc/default/ntpdate
by default.
.B ntpdate
sets the local date and time by polling Network Time
Protocol (NTP) servers.
