.\" -*- nroff -*"
.TH  NTPSWEEP 1
.SH NAME
ntpsweep \- Sweep NTP Servers and Report Relationships
.SH SYNOPSIS
.B ntpsweep
[ \-\-help|\-\-peers|\-\-strip <string>] <file>|[\-\-host <hostname> ]

.SH DESCRIPTION
.B ntpsweep
prints per host given in <file> the NTP stratum level, the
clock offset in seconds, the daemon version, the operating system and
the processor.

.SH OPTIONS
.TP
.I \-\-help
Print this short help text and exit.
.TP
.I <file>
Specify the hosts file. File format is one hostname or ip number per
line. Lines beginning with # are considered as comment.
.TP
.I \-\-host <hostname>
Speficy a single host, bypassing the need for a hosts file.
.TP
.I \-\-peers
List all peers a host synchronizes to.
.TP
.I \-\-strip <string>
Strip <string> from hostnames.

.SH AUTHOR
Hans Lambermont.  Manpage by Bdale Garbee <bdale@gag.com> for the Debian
GNU/Linux distribution.
