.TH KSBA-CONFIG 1 "Dec 5, 2001" "libksba"
.SH NAME
ksba-config \- print libksba library configuration information
.SH SYNOPSIS
.B "ksba-config"
[\-\-prefix]
[\-\-exec-prefix]
[\-\-version]
[\-\-libs]
[\-\-cflags]

.SH DESCRIPTION
This prints out various configuration information for the ksba
library. It is useful for application building and packaging procedures.

.SH OPTIONS
.TP
.I \-\-version
Show version number.
.TP
.I \-\-prefix
Outputs the prefix used to install libksba. 
.TP
.I \-\-exec-prefix
Outputs the exec-prefix used to install libksba. 
.TP
.I \-\-cflags
Outputs include flags for the C compiler.
.TP
.I \-\-libs
Outputs library flags for the linker.

.SH AUTHOR
Matthias Urlichs   <smurf@debian.org>

