--- /dev/null	1969-12-31 16:00:00.000000000 -0800
+++ watch-3.2.7/Makefile	2013-07-15 22:02:33.000000000 -0700
@@ -0,0 +1,11 @@
+CC = /usr/gcc/4.4/bin/gcc
+CFLAGS = -I/usr/include/ncurses
+LDFLAGS = -Wl,-rpath/usr/gnu/lib -L/usr/gnu/lib
+LIBS = -lncurses
+SOURCE = watch.c
+PROG	= watch
+
+all: watch
+
+watch:
+	$(CC) $(CFLAGS) $(LDFLAGS) $(LIBS) -o $(PROG) $(SOURCE)
