#!/bin/bash
#

case "$1" in
  start)
        if [ ! -d /var/run/c-icap ]; then
	    mkdir /var/run/c-icap
	    chown cicap:cicap /var/run/c-icap
        fi
        echo "Starting $prog "
        su cicap -c "/usr/bin/c-icap"
        ;;
  stop)
        echo "Stopping $prog "
        /usr/bin/pkill -x c-icap
        ;;
  restart)
        $0 stop
        echo "Waiting for $prog to stop.\c"
        while ( /usr/bin/pgrep -x c-icap > /dev/null )
        do
                echo ".\c"
                sleep 1
        done
        echo
        sleep 1
        $0 start
        ;;
  refresh|reload)
        echo "Reloading c-icap daemon configuration: "
        /usr/bin/pkill -x -HUP c-icap
        ;;
  *)
        echo $"Usage: $0 { start|stop|refresh|reload|restart }"
        exit 1
esac

exit 0

