#! /bin/sh
#
# Copyright 2001,2002 by Dennis Schoen <ds@teuto.net>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free
# Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA  02111-1307  USA.

# Source debconf library
. /usr/share/debconf/confmodule

# Get ntop user

db_get ntop/user
USER=$RET
INITCFG=/var/lib/ntop/init.cfg
db_get ntop/interfaces
INTERFACES=$RET

if [ -n "$USER" ] ; then
    # Creating ntop group if he isn't already there
    if ! grep -q ^$USER: /etc/passwd; then
	echo Adding system user: $USER.
	adduser --system --group --home /var/lib/ntop $USER
    fi

    # make status dir owned by user
    if grep -q ^$USER: /etc/passwd; then
	chown -Rf $USER /var/lib/ntop
	chown -Rf $USER /var/log/ntop
    fi
fi

chmod o-rx /var/lib/ntop

echo USER=\"$USER\" > $INITCFG
echo INTERFACES=\"$INTERFACES\" >> $INITCFG

db_stop

if [ -x "/etc/init.d/ntop" ]; then
    update-rc.d ntop defaults >/dev/null
    if [ -x /usr/sbin/invoke-rc.d ] ; then
	invoke-rc.d ntop start || true
    else
        /etc/init.d/ntop start || true
    fi
fi

#DEBHELPER#
