include ../../../make-rules/shared-macros.mk
COMPONENT_NAME     =  Markdown
COMPONENT_VERSION  =  2.0.3
COMPONENT_SRC      =  $(COMPONENT_NAME)-$(COMPONENT_VERSION)
COMPONENT_ARCHIVE  =  $(COMPONENT_SRC).zip
COMPONENT_ARCHIVE_HASH = sha1:83d8501a6ea3c60e5cdf4e6ef24fe6df8ee5c86e
COMPONENT_ARCHIVE_URL  = http://pypi.python.org/packages/source/M/Markdown/$(COMPONENT_ARCHIVE)

include $(WS_TOP)/make-rules/prep.mk
include $(WS_TOP)/make-rules/ips.mk
include $(WS_TOP)/make-rules/setup.py.mk

build:      $(BUILD_32)
install:    $(INSTALL_32)

COMPONENT_TEST_TARGETS = test
test:       $(TEST_32)

BUILD_PKG_DEPENDENCIES = $(BUILD_TOOLS)

include $(WS_TOP)/make-rules/depend.mk

