#!/sbin/sh

. /lib/svc/share/smf_include.sh

case "$1" in 
'refresh')
	pkill -HUP -u clamav -P1 clamd
	pkill -HUP -u clamav -P1 freshclam
        ;;

'start')
	if (egrep -s '^Example' /etc/clamav/clamd.conf); then
		echo "clamd: Configuration file has not been customised."
	else
		/usr/sbin/clamd
	fi
	if (egrep -s '^Example' /etc/clamav/freshclam.conf); then
		echo "freshclam: Configuration file has not been customised."
	else
		/usr/bin/freshclam --daemon
	fi
	;;

'stop')
	# Kill the entire service contract
	smf_kill_contract $2 TERM 1 30
	ret=$?
	[ $ret -eq 1 ] && exit 1

	# If the contract did not empty after TERM, move on to KILL.
	if [ $ret -eq 2 ] ; then
		smf_kill_contract $2 KILL 1
	fi
	;;

*)
	echo "Usage: $0 { start | stop | refresh }"
	exit 1
	;;
esac
exit 0

