#!/usr/bin/sh

set -e

PATH=/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH

if [ "${BASEDIR:=/}" != "/" ]; then
    BASEDIR_OPT="-b $BASEDIR"
fi

case "$1" in
    configure)
        echo "Nexenta Core Platform 4.0 (b2) (Siddy/Illumos)" > /etc/issue
        echo "Nexenta Core Platform 4.0 (b2) (Siddy/Illumos)" > /etc/issue.net
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

exit 0
