#!/bin/ksh -p
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#

. /usr/lib/brand/dpkg/common.ksh

# States
# ZONE_STATE_CONFIGURED           0 (never see)
# ZONE_STATE_INCOMPLETE           1 (never see)
# ZONE_STATE_INSTALLED            2
# ZONE_STATE_READY                3
# ZONE_STATE_RUNNING              4
# ZONE_STATE_SHUTTING_DOWN        5
# ZONE_STATE_DOWN                 6
# ZONE_STATE_MOUNTED              7

# cmd
#
# ready			0
# boot			1
# halt			4

ZONENAME=$1
ZONEPATH=$2
state=$3
cmd=$4
ALTROOT=$5

# If we're not halting the zone, then just return.
if [ $cmd -eq 4 ]; then
	is_brand_labeled
	if (( $? == 0 )); then
		# Leave the active dataset mounted after halting (this might be
		# a different dataset than what was mounted).
		mount_active_ds
	else
		# Umount dataset on the root.
		zoneroot="$ZONEPATH/root"
		umount -f $zoneroot || printf "$f_zfs_unmount" "$zoneroot"
	fi
fi

exit $ZONE_SUBPROC_OK
