#!/bin/sh
set -eu

# Doc base
if [ "$1" = "configure" ] ; then
# if command -v install-docs >/dev/null 2>&1; then
#   install-docs -i /usr/share/doc-base/bzip2
# fi
  if test -x /usr/sbin/install-docs >/dev/null 2>&1; then
    /usr/sbin/install-docs -i /usr/share/doc-base/bzip2
  fi
fi

# Info
install-info --quiet --section "General Commands" "General Commands" \
    /usr/share/info/bzip2.info
