#!/bin/sh -e

compute_revision()
{
  export max
  srcdir="$1"
  cd "$srcdir"
  declare -x max
  max=0
  svn status -v | ( while read a b rest ; do
    declare -x max
    if [ "$max" -lt "$b" ] ; then
      max=$b
    fi
  done
  echo "$max"
  )
}


sourcedir=/src/TeX/TeXLive/Build/source

if [ "$1" = "-download" ] ; then
  use_downloaded_source=false
  shift
else
  use_downloaded_source=true
  if [ "$1" = "-sourcedir" ] ; then
    shift
    sourcedir="$1"
    shift
  fi
fi

if [ "$1" = "-rev" ] ; then
  rev=`compute_revision "$sourcedir"`
  echo "compute revision: $rev"
  exit 0
fi

target=$(pwd)
V=2009~
NAME=texlive-bin_$V
dircomponent=texlive-bin-$V

cleanup()
{
    exit $rc
    [ -n "$tempdir" ] && rm -rf "$tempdir"
    exit $rc
}


if ! [ "$use_downloaded_source" = "true" ]; then
  tempdir=$(mktemp -d)
  trap 'cleanup 0' HUP INT QUIT BUS PIPE TERM
  cd $tempdir
  svn co svn://tug.org/texlive/trunk/Build/source
  sourcedir=./source
  revision=`compute_revision "$sourcedir"`
  #revision=$(cd $sourcedir;svn info | sed -n -e '/Revision:/{s/Revision: //;p}')
  find source -name ".svn" | xargs rm -r
  cd $target
  sourcedir=$tempdir/Build/source
else
  revision=`compute_revision "$sourcedir"`
  #revision=$(cd $sourcedir;svn info | sed -n -e '/Revision:/{s/Revision: //;p}')
fi



do_tar ()
{
  verbose="-v --show-transformed-names"
  compress=-z
  tar_common_opt="--exclude-vcs $compress $verbose"
  #
  dir=$1
  shift
  name=$1
  shift
  tarfile=$target/$name.tar.gz
  tar -cf "$tarfile" --owner=0 --group=0 \
      --transform="s,^,$dir/," $tar_common_opt \
      "$@"
  (cd $target && sha256sum `basename $tarfile`) >$tarfile.sha256
  ls -l "$tarfile"
}


cd $sourcedir
do_tar ${dircomponent}svn$revision ${NAME}svn$revision.orig *
