#!/bin/bash

if [ "$1" == "--help" ] ; then
    echo \`$PNAME\' 
    echo
    $MPATH/$PNAME $1 2>&1 #| \
#    awk '/where options include/ {next} {print}' |\
#    awk '/ATLAS usage:/ {i=1;next} {if (i) {$0="Usage: " $0;i=0};print}'
else
    echo $PNAME $VERSION
    echo
#    echo Copyright \(C\) 2002 R. Clint Whaley et. al.
#    awk '/^Copyright/ {i=1;next} {if (i) print}' /usr/share/doc/atlas2-base/copyright 
#    echo
#    echo Written by R. Clint Whaley, et. al.
fi
exit 0
